// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BYEiDAQtt_C2pladSl5Aqn2mmo_DIjg',
    appId: '1:705509023681:web:e99ef2559d457e568f5940',
    messagingSenderId: '705509023681',
    projectId: 'datastellar-f3ba9',
    authDomain: 'datastellar-f3ba9.firebaseapp.com',
    databaseURL: 'https://datastellar-f3ba9-default-rtdb.firebaseio.com',
    storageBucket: 'datastellar-f3ba9.appspot.com',
    measurementId: 'G-JBPB4ZG14F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvGXDeGwb51Dmcz4JM_Nqe3OodvTmt_s',
    appId: '1:705509023681:android:627fb4e73ec9bc548f5940',
    messagingSenderId: '705509023681',
    projectId: 'datastellar-f3ba9',
    databaseURL: 'https://datastellar-f3ba9-default-rtdb.firebaseio.com',
    storageBucket: 'datastellar-f3ba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ZSm91ZXfo901VApTUYt234y2LMCUyek',
    appId: '1:705509023681:ios:b5bf4d45f53a35638f5940',
    messagingSenderId: '705509023681',
    projectId: 'datastellar-f3ba9',
    databaseURL: 'https://datastellar-f3ba9-default-rtdb.firebaseio.com',
    storageBucket: 'datastellar-f3ba9.appspot.com',
    androidClientId: '705509023681-0qjjr4r8ppb9cjhhnddpjtk918mf3kav.apps.googleusercontent.com',
    iosClientId: '705509023681-dasbbgel6617cd9i0so3rouo0ffsseia.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ZSm91ZXfo901VApTUYt234y2LMCUyek',
    appId: '1:705509023681:ios:b5bf4d45f53a35638f5940',
    messagingSenderId: '705509023681',
    projectId: 'datastellar-f3ba9',
    databaseURL: 'https://datastellar-f3ba9-default-rtdb.firebaseio.com',
    storageBucket: 'datastellar-f3ba9.appspot.com',
    androidClientId: '705509023681-0qjjr4r8ppb9cjhhnddpjtk918mf3kav.apps.googleusercontent.com',
    iosClientId: '705509023681-dasbbgel6617cd9i0so3rouo0ffsseia.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
